image: docker:latest

services:
  - docker:dind

stages:
  - build

verificar_container:
  stage: build
  script:
    - echo "Iniciando o build da imagem Docker..."
    - docker build -t app-votacao .
    - echo "Build conclu√≠do com sucesso!"